services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy # can be changed
    environment:
      - LANG=en
      - WG_HOST=myhost.com #  change this to your domain or public ip
      - PORT=51821 # frontend port
      - WG_PORT=51820 # vpn port
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=2 # 0, 1, 2 or 3
      - WG_ALLOWED_IPS=0.0.0.0/0,::/0
    volumes:
      - ./data:/etc/wireguard
    ports:
      - "51820:51820/udp" # vpn port (must be udp)
      - "51821:51821/tcp" # frontend port (must be tcp)
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped